package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AGroups generated by hbm2java
 */
public class AGroups  implements java.io.Serializable {


     private String groupName;
     private String description;
     private Set AUserses = new HashSet(0);

    public AGroups() {
    }

	
    public AGroups(String groupName, String description) {
        this.groupName = groupName;
        this.description = description;
    }
    public AGroups(String groupName, String description, Set AUserses) {
       this.groupName = groupName;
       this.description = description;
       this.AUserses = AUserses;
    }
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getAUserses() {
        return this.AUserses;
    }
    
    public void setAUserses(Set AUserses) {
        this.AUserses = AUserses;
    }




}


