package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AUsers generated by hbm2java
 */
public class AUsers  implements java.io.Serializable {


     private String username;
     private String password;
     private boolean accountEnabled;
     private boolean accountExpired;
     private boolean accountLocked;
     private boolean credentialsExpired;
     private String salt;
     private boolean nonNaturalPerson;
     private Set AGroupses = new HashSet(0);

    public AUsers() {
    }

	
    public AUsers(String username, String password, boolean accountEnabled, boolean accountExpired, boolean accountLocked, boolean credentialsExpired, String salt, boolean nonNaturalPerson) {
        this.username = username;
        this.password = password;
        this.accountEnabled = accountEnabled;
        this.accountExpired = accountExpired;
        this.accountLocked = accountLocked;
        this.credentialsExpired = credentialsExpired;
        this.salt = salt;
        this.nonNaturalPerson = nonNaturalPerson;
    }
    public AUsers(String username, String password, boolean accountEnabled, boolean accountExpired, boolean accountLocked, boolean credentialsExpired, String salt, boolean nonNaturalPerson, Set AGroupses) {
       this.username = username;
       this.password = password;
       this.accountEnabled = accountEnabled;
       this.accountExpired = accountExpired;
       this.accountLocked = accountLocked;
       this.credentialsExpired = credentialsExpired;
       this.salt = salt;
       this.nonNaturalPerson = nonNaturalPerson;
       this.AGroupses = AGroupses;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAccountEnabled() {
        return this.accountEnabled;
    }
    
    public void setAccountEnabled(boolean accountEnabled) {
        this.accountEnabled = accountEnabled;
    }
    public boolean isAccountExpired() {
        return this.accountExpired;
    }
    
    public void setAccountExpired(boolean accountExpired) {
        this.accountExpired = accountExpired;
    }
    public boolean isAccountLocked() {
        return this.accountLocked;
    }
    
    public void setAccountLocked(boolean accountLocked) {
        this.accountLocked = accountLocked;
    }
    public boolean isCredentialsExpired() {
        return this.credentialsExpired;
    }
    
    public void setCredentialsExpired(boolean credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public boolean isNonNaturalPerson() {
        return this.nonNaturalPerson;
    }
    
    public void setNonNaturalPerson(boolean nonNaturalPerson) {
        this.nonNaturalPerson = nonNaturalPerson;
    }
    public Set getAGroupses() {
        return this.AGroupses;
    }
    
    public void setAGroupses(Set AGroupses) {
        this.AGroupses = AGroupses;
    }




}


