package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GCountries generated by hbm2java
 */
public class GCountries  implements java.io.Serializable {


     private String iso3166a2;
     private GZones GZones;
     private String phoneCode;
     private Set PPhoneses = new HashSet(0);
     private Set PJuridicalPersons = new HashSet(0);

    public GCountries() {
    }

	
    public GCountries(String iso3166a2) {
        this.iso3166a2 = iso3166a2;
    }
    public GCountries(String iso3166a2, GZones GZones, String phoneCode, Set PPhoneses, Set PJuridicalPersons) {
       this.iso3166a2 = iso3166a2;
       this.GZones = GZones;
       this.phoneCode = phoneCode;
       this.PPhoneses = PPhoneses;
       this.PJuridicalPersons = PJuridicalPersons;
    }
   
    public String getIso3166a2() {
        return this.iso3166a2;
    }
    
    public void setIso3166a2(String iso3166a2) {
        this.iso3166a2 = iso3166a2;
    }
    public GZones getGZones() {
        return this.GZones;
    }
    
    public void setGZones(GZones GZones) {
        this.GZones = GZones;
    }
    public String getPhoneCode() {
        return this.phoneCode;
    }
    
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode;
    }
    public Set getPPhoneses() {
        return this.PPhoneses;
    }
    
    public void setPPhoneses(Set PPhoneses) {
        this.PPhoneses = PPhoneses;
    }
    public Set getPJuridicalPersons() {
        return this.PJuridicalPersons;
    }
    
    public void setPJuridicalPersons(Set PJuridicalPersons) {
        this.PJuridicalPersons = PJuridicalPersons;
    }




}


