package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GZones generated by hbm2java
 */
public class GZones  implements java.io.Serializable {


     private long zoneId;
     private String poligone;
     private String name;
     private Short level;
     private Long parentZone;
     private Set GLocationses = new HashSet(0);
     private Set GCountrieses = new HashSet(0);

    public GZones() {
    }

	
    public GZones(long zoneId) {
        this.zoneId = zoneId;
    }
    public GZones(long zoneId, String poligone, String name, Short level, Long parentZone, Set GLocationses, Set GCountrieses) {
       this.zoneId = zoneId;
       this.poligone = poligone;
       this.name = name;
       this.level = level;
       this.parentZone = parentZone;
       this.GLocationses = GLocationses;
       this.GCountrieses = GCountrieses;
    }
   
    public long getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(long zoneId) {
        this.zoneId = zoneId;
    }
    public String getPoligone() {
        return this.poligone;
    }
    
    public void setPoligone(String poligone) {
        this.poligone = poligone;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Short getLevel() {
        return this.level;
    }
    
    public void setLevel(Short level) {
        this.level = level;
    }
    public Long getParentZone() {
        return this.parentZone;
    }
    
    public void setParentZone(Long parentZone) {
        this.parentZone = parentZone;
    }
    public Set getGLocationses() {
        return this.GLocationses;
    }
    
    public void setGLocationses(Set GLocationses) {
        this.GLocationses = GLocationses;
    }
    public Set getGCountrieses() {
        return this.GCountrieses;
    }
    
    public void setGCountrieses(Set GCountrieses) {
        this.GCountrieses = GCountrieses;
    }




}


