package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PEmails generated by hbm2java
 */
public class PEmails  implements java.io.Serializable {


     private String emailAddress;
     private PEmailTypes PEmailTypes;
     private boolean isOperational;
     private Set PJuridicalPersons = new HashSet(0);
     private Set PNaturalPersons = new HashSet(0);

    public PEmails() {
    }

	
    public PEmails(String emailAddress, PEmailTypes PEmailTypes, boolean isOperational) {
        this.emailAddress = emailAddress;
        this.PEmailTypes = PEmailTypes;
        this.isOperational = isOperational;
    }
    public PEmails(String emailAddress, PEmailTypes PEmailTypes, boolean isOperational, Set PJuridicalPersons, Set PNaturalPersons) {
       this.emailAddress = emailAddress;
       this.PEmailTypes = PEmailTypes;
       this.isOperational = isOperational;
       this.PJuridicalPersons = PJuridicalPersons;
       this.PNaturalPersons = PNaturalPersons;
    }
   
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public PEmailTypes getPEmailTypes() {
        return this.PEmailTypes;
    }
    
    public void setPEmailTypes(PEmailTypes PEmailTypes) {
        this.PEmailTypes = PEmailTypes;
    }
    public boolean isIsOperational() {
        return this.isOperational;
    }
    
    public void setIsOperational(boolean isOperational) {
        this.isOperational = isOperational;
    }
    public Set getPJuridicalPersons() {
        return this.PJuridicalPersons;
    }
    
    public void setPJuridicalPersons(Set PJuridicalPersons) {
        this.PJuridicalPersons = PJuridicalPersons;
    }
    public Set getPNaturalPersons() {
        return this.PNaturalPersons;
    }
    
    public void setPNaturalPersons(Set PNaturalPersons) {
        this.PNaturalPersons = PNaturalPersons;
    }




}


