package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PJuridicalPerson generated by hbm2java
 */
public class PJuridicalPerson  implements java.io.Serializable {


     private long juridicalPersonId;
     private GCountries GCountries;
     private GLocations GLocations;
     private String name;
     private Date registrationDate;
     private Set PEmailses = new HashSet(0);
     private Set PPhoneses = new HashSet(0);

    public PJuridicalPerson() {
    }

	
    public PJuridicalPerson(long juridicalPersonId, GCountries GCountries, GLocations GLocations, String name, Date registrationDate) {
        this.juridicalPersonId = juridicalPersonId;
        this.GCountries = GCountries;
        this.GLocations = GLocations;
        this.name = name;
        this.registrationDate = registrationDate;
    }
    public PJuridicalPerson(long juridicalPersonId, GCountries GCountries, GLocations GLocations, String name, Date registrationDate, Set PEmailses, Set PPhoneses) {
       this.juridicalPersonId = juridicalPersonId;
       this.GCountries = GCountries;
       this.GLocations = GLocations;
       this.name = name;
       this.registrationDate = registrationDate;
       this.PEmailses = PEmailses;
       this.PPhoneses = PPhoneses;
    }
   
    public long getJuridicalPersonId() {
        return this.juridicalPersonId;
    }
    
    public void setJuridicalPersonId(long juridicalPersonId) {
        this.juridicalPersonId = juridicalPersonId;
    }
    public GCountries getGCountries() {
        return this.GCountries;
    }
    
    public void setGCountries(GCountries GCountries) {
        this.GCountries = GCountries;
    }
    public GLocations getGLocations() {
        return this.GLocations;
    }
    
    public void setGLocations(GLocations GLocations) {
        this.GLocations = GLocations;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }
    public Set getPEmailses() {
        return this.PEmailses;
    }
    
    public void setPEmailses(Set PEmailses) {
        this.PEmailses = PEmailses;
    }
    public Set getPPhoneses() {
        return this.PPhoneses;
    }
    
    public void setPPhoneses(Set PPhoneses) {
        this.PPhoneses = PPhoneses;
    }




}


