package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PPhones generated by hbm2java
 */
public class PPhones  implements java.io.Serializable {


     private long phoneId;
     private GCountries GCountries;
     private PPhoneTypes PPhoneTypes;
     private long phoneNumber;
     private boolean isOperational;
     private Set PNaturalPersons = new HashSet(0);
     private Set PJuridicalPersons = new HashSet(0);

    public PPhones() {
    }

	
    public PPhones(long phoneId, GCountries GCountries, PPhoneTypes PPhoneTypes, long phoneNumber, boolean isOperational) {
        this.phoneId = phoneId;
        this.GCountries = GCountries;
        this.PPhoneTypes = PPhoneTypes;
        this.phoneNumber = phoneNumber;
        this.isOperational = isOperational;
    }
    public PPhones(long phoneId, GCountries GCountries, PPhoneTypes PPhoneTypes, long phoneNumber, boolean isOperational, Set PNaturalPersons, Set PJuridicalPersons) {
       this.phoneId = phoneId;
       this.GCountries = GCountries;
       this.PPhoneTypes = PPhoneTypes;
       this.phoneNumber = phoneNumber;
       this.isOperational = isOperational;
       this.PNaturalPersons = PNaturalPersons;
       this.PJuridicalPersons = PJuridicalPersons;
    }
   
    public long getPhoneId() {
        return this.phoneId;
    }
    
    public void setPhoneId(long phoneId) {
        this.phoneId = phoneId;
    }
    public GCountries getGCountries() {
        return this.GCountries;
    }
    
    public void setGCountries(GCountries GCountries) {
        this.GCountries = GCountries;
    }
    public PPhoneTypes getPPhoneTypes() {
        return this.PPhoneTypes;
    }
    
    public void setPPhoneTypes(PPhoneTypes PPhoneTypes) {
        this.PPhoneTypes = PPhoneTypes;
    }
    public long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public boolean isIsOperational() {
        return this.isOperational;
    }
    
    public void setIsOperational(boolean isOperational) {
        this.isOperational = isOperational;
    }
    public Set getPNaturalPersons() {
        return this.PNaturalPersons;
    }
    
    public void setPNaturalPersons(Set PNaturalPersons) {
        this.PNaturalPersons = PNaturalPersons;
    }
    public Set getPJuridicalPersons() {
        return this.PJuridicalPersons;
    }
    
    public void setPJuridicalPersons(Set PJuridicalPersons) {
        this.PJuridicalPersons = PJuridicalPersons;
    }




}


