package ca.danielvega.hibernatestruts.model.entities;
// Generated 29-Mar-2016 2:41:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PPhoneTypes generated by hbm2java
 */
public class PPhoneTypes  implements java.io.Serializable {


     private String phoneType;
     private String description;
     private Set PPhoneses = new HashSet(0);

    public PPhoneTypes() {
    }

	
    public PPhoneTypes(String phoneType, String description) {
        this.phoneType = phoneType;
        this.description = description;
    }
    public PPhoneTypes(String phoneType, String description, Set PPhoneses) {
       this.phoneType = phoneType;
       this.description = description;
       this.PPhoneses = PPhoneses;
    }
   
    public String getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPPhoneses() {
        return this.PPhoneses;
    }
    
    public void setPPhoneses(Set PPhoneses) {
        this.PPhoneses = PPhoneses;
    }




}


